name: Request a certificate  


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  request-certificate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Fulcio CLI
      run: |
            curl -LO https://github.com/sigstore/fulcio/releases/latest/download/fulcio-linux-amd64
            mv fulcio-linux-amd64 fulcio
            chmod +x fulcio
            sudo mv fulcio /usr/local/bin/fulcio
            fulcio version
            
    - name: Install Rekor CLI
      run: |
          curl -sSL https://github.com/sigstore/rekor/releases/latest/download/rekor-cli-linux-amd64 \
            -o rekor
          chmod +x rekor
          sudo mv rekor /usr/local/bin/
          
    - name: Sign Artifact with Rekor
      run: |
          rekor upload --artifact hulk-app9-showtym-devops-backend-0.0.1-SNAPSHOT.jar 
    



